blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ DÃºvida/Suporte Geral
    url: https://github.com/eps-fcte-2025-2/alm-backend/discussions/new?category=q-a
    about: FaÃ§a uma pergunta sobre uso ou procure suporte em nosso fÃ³rum da comunidade (Discussions).
  - name: ğŸ›¡ï¸ Relatar uma Vulnerabilidade de SeguranÃ§a
    url: https://github.com/eps-fcte-2025-2/alm-backend/security/policy
    about: Para divulgaÃ§Ã£o responsÃ¡vel, por favor, reporte problemas de seguranÃ§a de forma privada.